import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillGithub , AiFillTwitterCircle, AiFillLinkedin} from 'react-icons/ai';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Elchin Gonagov Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='px-10'>
        <section className=" min-h-screen">
          <nav className='py-10 mb-12 flex justify-between'>
          <h1 className="text-xl  font-burtons">developdbyed</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill className='cursor-pointer text-2xl'/>
              </li>
              <li>
                <a className="bg-green-400 text-white px-4 py-2 rounded-md ml-8" href="#">Resume</a>
              </li>
            </ul>
          </nav>
          <div>
            <h2>Elchin Gonagov</h2>
            <h3>Front-end Developer</h3>
            <p>I’m a mysterious individual who has yet to fill out my bio. One thing’s for certain: I love writing front-end code!</p>
          </div>
          <div>
            <AiFillTwitterCircle/>
            <AiFillLinkedin/>
            <AiFillGithub/>
          </div>

        </section>
        
      </main>
    </>
  )
}
